export const FETCH_NOTES = "FETCH_NOTES";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_FAILURE = "FETCH_NOTES_FAILURE";

export const SORT_NOTES = "SORT_NOTES";
export const SET_ACTIVE_NOTE = "SET_ACTIVE_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const ADD_NOTE = "ADD_NOTE";
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
