export const FETCH_NOTEBOOKS = "FETCH_NOTEBOOKS";
export const FETCH_NOTEBOOKS_SUCCESS = "FETCH_NOTEBOOKS_SUCCESS";
export const FETCH_NOTEBOOKS_FAILURE = "FETCH_NOTEBOOKS_FAILURE";

export const SET_ACTIVE_NOTEBOOKS = "SET_ACTIVE_NOTEBOOKS";
export const ADD_NOTEBOOK = "ADD_NOTEBOOK";
